- name: Install zplug
  become: yes
  become_user: "{{ username }}"
  shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  args:
    warn: false

- name: Install zplug for root
  shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  args:
    warn: false

- name: Install starship shell
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- -y
  args:
    warn: false

- name: Remove .zshrc after it was created by oh-my-zsh installation
  become: yes
  become_user: "{{ username }}"
  file:
    path: ~/.zshrc
    state: absent
